### ISSUE TITLE
xi-rope crate is old in crago registry

### ISSUE THREAD

**Issue by ngortheone** [xi-editor/xi-editor#1119]
Hi. It looks like xi-rope crate is outdated on crates.io

https://crates.io/crates/xi-rope

```
$ cargo search xi-rope
xi-rope = "0.2.0"    # A generic rope data structure built on top of B-Trees.
```
This repo contains `0.3.0` version.  Is this intentional? Is this crate intended for internal use only?
How can I import latest xi-rope into my project?

**Comment by cmyr** [comment]
@ngortheone we've gotten bad at publishing crates to crates.io.

To use the version in this repo, you can do:
```toml
[dependencies.xi-rope]
git = "https://github.com/xi-editor/xi-editor.git"
branch = "master"
# or: commit = F0F0F0F
```
